### PR TITLE
Fix timing bug

### PR DESCRIPTION
**Pull request by FrankvdStam**
Fix an access denied bug causing timers to break when trying to delete ResetAllStats.exe while still executing it. Made the .exe run asynchronously to not block timers

### CODE REVIEW

**Comment by FrankvdStam** [comment]
Xero (discord Xero#4555) is using this now for testing, has so far reported the issue to be resolved.

**Review by CapitaineToinon — CHANGES_REQUESTED** [review]
Hey, thanks for PR, much appreciated. I never encountered this problem but this solution makes sense. 

However could you also update the `update.LiveSplit.ResetAllStats.xml` file and the binary's internal version to match the new one in order to have the auto update processing working? This project isn't using semver so you can just make a 4.0 version. 

Thank you very much!

**Comment by FrankvdStam** [comment]
Yeah sure. Is that the only place where an update is needed, or does it also need assembly info version changes?
Would assume this: https://github.com/CapitaineToinon/LiveSplit.ResetAllStats/blob/4fdd3dd41dc337b1f9511aef73929e262844817d/LiveSplit.ResetAllStats/Properties/AssemblyInfo.cs#L35
has to be bumped to 4 as well.

**Comment by CapitaineToinon** [comment]
Yes, change AssemblyVersion to 4.0.0.0, match the version in `update.LiveSplit.ResetAllStats.xml` and recompile the dll. Then livesplit will be able to automatically download and install the new version. 👍 Sorry I wasn't clear enough on my first message.

**Comment by FrankvdStam** [comment]
Bumped the version, should be good now

**Pull request merged**
